fix: added d2l-tooltip to tell user limit was reached
BrightspaceUILabs/attribute-picker pull request #55
Opened 2021-09-27 20:11 UTC by ChrisLabattD2L

As a part of [US126159](https://rally1.rallydev.com/#/357252275780d/dashboard?detail=%2Fuserstory%2F512835224632), this change helps inform the user that the limit of attributes has been reached. If no limit is set, then the tooltip should not appear.

2021-09-28 19:22 UTC, BhamelinD2L commented on attribute-picker.js
> +		this._tooltipFocus();
The description in miro says `triggered on focus of the input` but this is happening on mouse hover, not focus. If your mouse is in the wrong place because you tabbed to access the input, you won't get the tooltip to appear.

2021-09-28 20:41 UTC, ChrisLabattD2L commented
@BhamelinD2L I've made the changes that you've suggested, don't be afraid to let me know if you find anything else! 😄

2021-09-29 19:21 UTC, BhamelinD2L commented on attribute-picker.js
> +					@mouseout="${this._tooltipUnfocus}">
I think this still needs to be removed, because it results in hiding the tooltip if you mouse over the list and then away

2021-09-29 19:25 UTC, BhamelinD2L requested changes
One small change suggestion left, otherwise looks good!

2021-09-29 19:53 UTC, ChrisLabattD2L commented on attribute-picker.js
> +					@mouseout="${this._tooltipUnfocus}">
@BhamelinD2L That's the intention of it, the tooltip should only appear when the user is within the text field as well as the list below it. That way they aren't confused as to why they can't select anything. The event is mostly in place to account for the situation when the used exits through the list that appears below instead of through the text field above.

2021-10-04 15:14 UTC, closed without merging