Fix for incorrect match count due to casing error
BrightspaceUILabs/attribute-picker pull request #57
Opened 2021-10-13 22:32 UTC by remytruong

I simply made everything lowercase for matching - was thinking about adding a way for other things using attribute picker to pass in a filter function, but thought that was a bit unnecessary.

2021-11-01 15:50 UTC, ChrisLabattD2L requested changes
Some changes may need to be made to still allow the user to enter in attributes that are substrings of other options.
Also, be sure to review the tests that are failing so you know whether or not it's your code that needs to change or if the rules need to be updated.

2021-11-01 15:50 UTC, ChrisLabattD2L commented on attribute-picker.js
> +			this.allowFreeform ? this._dropdownIndex = 0 : this._dropdownIndex = 0;
The ternary operator here is useless now and can be removed since the end result is the same for both.

2021-11-01 15:50 UTC, ChrisLabattD2L commented on attribute-picker.js
> +					this._dropdownIndex = 0;
By changing `_dropdownIndex` to be 0, you are prohibiting the user from entering an option that is a substring of another option. I.e. if you want to enter `four` as an option and `fourteen` is an option (pretend it's NOT available in the dropdown choice of attributes to choose from) , it will force the user to have to select `fourteen` instead of letting the user add in the option of `four`

2021-11-01 15:50 UTC, ChrisLabattD2L commented on attribute-picker.js
> +			this._dropdownIndex = 0;
Since the user may not have typed anything in at this point, it may be worth having the select option remain as `-1` and only potentially change the index once the user starts typing something in.

2021-11-01 19:40 UTC, remytruong commented on attribute-picker.js
> +					this._dropdownIndex = 0;
Is there ever a case of a user having an attribute that wouldn't show up on the dropdown list though? That would mean that if the 'four' option didn't exist, then it wouldn't be a valid attribute and thus would match with zero users. In that case, the subliminal message is to enter a valid option from the list. In that case, the dropdown might as well not exist, and the user should be able to free-form type in whatever they want?

2021-11-02 15:33 UTC, BhamelinD2L commented on attribute-picker.js
> +					this._dropdownIndex = 0;
The component is more generic than just our use case. There's value in allowing it to function as a list of suggestions in another application, that has nothing to do with matching user counts with attributes. Imagine a use case where a user needs to create a collection of new or existing tags to describe a course for example.  It's not reasonable to have to build an entire new component for that case when this component can cover it.

Note that there is an option to specify this behavior as desirable or not - `allow-freeform`. It needs to retain the ability to operate one way with that on, and one way with that off.

2021-11-02 18:55 UTC, remytruong commented on attribute-picker.js
> +			this.allowFreeform ? this._dropdownIndex = 0 : this._dropdownIndex = 0;
Reverted - don't need this anymore

2021-11-02 18:56 UTC, remytruong commented on attribute-picker.js
> +					this._dropdownIndex = 0;
Okay - it simply just matches for incorrect casing now (but the same word). ex. 'FoUr' will be corrected to the attribute listed 'four'

2021-11-02 19:33 UTC, ChrisLabattD2L approved these changes
Looks good now, the tests I was trying worked as expected!
I'd suggest maybe waiting for @BhamelinD2L to do his last check, but it looks good to me right now!

2021-11-03 17:18 UTC, BhamelinD2L commented on attribute-picker.js
> +					let attributeListStandardized = [];
This line is creating a new array that is unused. The variable is reassigned by the line `attributeListStandardized = this.attributeList.map((item) => {` into a brand new array containing the mapped items.

We can therefore remove this line and just append `const` to the following assignment.

2021-11-03 17:22 UTC, remytruong commented on attribute-picker.js
> +					let attributeListStandardized = [];
Done!

2021-11-03 17:22 UTC, BhamelinD2L commented on attribute-picker.js
>  					}
Let me introduce you to my friend the [Guard Clause](https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html)

We can reduce the nesting of if statements here and get clearer code, as well as avoid the work of unnecessarily calculating the matchedIndex, by inverting your if statement and placing it above that work. 

```suggestion
					if (trimmedAttribute.length === 0 || attributeListStandardized.includes(trimmedAttribute)) {
						return;
					}

					const matchedIndex = this.assignableAttributes.map((item) => {
						return item.toLowerCase();
					}).findIndex((x) => {
						return x === trimmedAttribute;
					});

					if (matchedIndex >= 0) {
						this.addAttribute(this.assignableAttributes[matchedIndex]);
					} else {
						this.addAttribute(this._text.trim());
					}
```

2021-11-03 17:25 UTC, BhamelinD2L requested changes
Couple tiny suggestions - You should be all set after this, thank you!

2021-11-03 17:30 UTC, remytruong commented on attribute-picker.js
>  					}
Aaah I rarely ever think of guard clauses - thank you!

2021-11-03 17:41 UTC, BhamelinD2L approved these changes
I believe you remember, but just in case - 
A commit needs to be prefixed with `fix` (PR title will not trigger the build). Make sure when you press 'Merge', `fix:` prefixes the commit name, so that the merge commit itself contains it.

2021-11-03 18:04 UTC, merged